### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by haiman233** [Sefiraat/SlimeTinker#14]
Java Environment:
  Operating System: Linux
  Java Version: 16.0.1

Server Software: Yatopia
  Build: git-Yatopia-ver/1.16.5-115 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v1.1.9_货运极致优化
  Caused by: SlimeCustomizer vDEV - 8 (git 6fe1c3e1)
Installed Addons (6)
  - SlimeCustomizer DEV - 8 (git 6fe1c3e1)
  + SlimeTinker MODIFIED
  + InfinityExpansion 144 - CH
  + DynaTech 1.0.0
  + ExoticGarden DEV - 75 (git 6c3e5412)
  + Bump 1.0
Block Info:
  World: bskyblock_world
  X: -778
  Y: 62
  Z: 36
  Material: CHISELED_POLISHED_BLACKSTONE
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: SMELTERY_CONTROLLER
  Inventory: true
  Data: {"id":"SMELTERY_CONTROLLER","tnk-lava-level":"1000"}
Stacktrace:

java.lang.NullPointerException: Cannot read field "meltingRecipes" because the return value of "io.github.sefiraat.slimetinker.SlimeTinker.getCmManager()" is null
	at io.github.sefiraat.slimetinker.utils.ItemUtils.getMoltenResult(ItemUtils.java:221)
	at io.github.sefiraat.slimetinker.items.workstations.smeltery.TinkersSmelteryCache.input(TinkersSmelteryCache.java:79)
         at io.github.sefiraat.slimetinker.items.workstations.smeltery.TinkersSmelteryCache.process(TinkersSmelteryCache.java:106)
	at io.github.sefiraat.slimetinker.items.workstations.smeltery.TinkersSmeltery$1.tick(TinkersSmeltery.java:62)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:180)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:161)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1514)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:443)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1423)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1144)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Sefiraat** [comment]
SlimeTinker MODIFIED <- This means you are not running a 'release' build. I'm not sure how you got this unless you compiled it yourself? Either way, I cant support bugs in a build that i've not released? Also, which you posted the error, you've not given any detail on what you did to get it or any info surrounding it.

Please download the correct version from the Slimefun Builds page and you should not receive this issue.

Sefi
