### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by anthonykour** [Sefiraat/SlimeTinker#190]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

`[21:31:44 INFO]: [SlimeTinker] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[21:31:44 INFO]: [SlimeTinker] [ACF] java.lang.NoSuchFieldException: locale
[21:31:44 INFO]: [SlimeTinker] [ACF]    at java.base/java.lang.Class.getDeclaredField(Class.java:2663)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at SlimeTinker - DEV 84 (git 2c9f6).jar//io.github.sefiraat.slimetinker.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:317)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at SlimeTinker - DEV 84 (git 2c9f6).jar//io.github.sefiraat.slimetinker.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1351)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1328)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1321)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1299)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1187)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:31:44 INFO]: [SlimeTinker] [ACF]    at java.base/java.lang.Thread.run(Thread.java:1589)`

### Steps to reproduce

1. place jar in plugins folder
2. start server
3. running on purpur 1.20.2

### Expected behavior

not throw a console error for player preferred language

### Server software

Purpur

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

Slimefun4

### SlimeTinker version

Slimefun4 - DEV 1104 (git c9774)

### Other plugins

>....[23:03:27 INFO]: Paper Plugins: (3):
[23:03:27 INFO]:  - MarriageMaster, Minepacks, PCGF_PluginLib
[23:03:27 INFO]: Bukkit Plugins: (43):
[23:03:27 INFO]:  - ActivityRewarder, AntiPopup, BetterChairs, BetterCommandSpy, BetterConcrete, BetterRTP, Brewery, *ClearConsole, CMILib, CoreProtect
[23:03:27 INFO]:  DoorsReloaded, Elevator, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExoticGarden, FastAsyncWorldEdit, FluffyMachines, GriefPrevention
[23:03:27 INFO]:  HeadDatabase, InventoryRollbackPlus, Jobs, LuckPerms, LWC, mcMMO, MineTweaks, MobCapturer, NBTAPI, NoChatReports
[23:03:27 INFO]:  PlaceholderAPI, ProtocolLib, RHLeafDecay, SilkSpawners, Slimefun, SlimeTinker, Smelter, spark, TAB, TreeFeller
[23:03:27 INFO]:  Vault, WildStacker, WorldGuard

**Comment by ybw0014** [comment]
please use pastebin to provide stacktrace instead of putting them here directly

**Comment by anthonykour** [comment]
https://pastebin.com/j9xMtp1g
