### ISSUE TITLE
Problem with loading SlimeTinker on my server

### ISSUE THREAD

**Issue by OldLord-dev** [Sefiraat/SlimeTinker#52]
## Description (Required)
During starting server i got error log in the console. Server works with this error but in game i see just slime tinker tabs without any items inside i cant use plugin. 

## Steps to reproduce the Issue (Required)
Turn on server

## Expected behavior (Required)
Working SlimeTinker on my server

## Server Log / Error Report
[14:30:36] [Server thread/ERROR]: [SlimeTinker] The following error has occurred during SlimeTinker's startup!
[14:30:36] [Server thread/ERROR]: [SlimeTinker] Not all items and features will be available because of this!
[14:30:36] [Server thread/ERROR]: [SlimeTinker] Report this on Github or Discord and make sure to update Slimefun!
[14:30:36] [Craft Scheduler Thread - 0/INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[14:30:36] [Craft Scheduler Thread - 0/WARN]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[14:30:36] [Craft Scheduler Thread - 0/INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[14:30:36] [Craft Scheduler Thread - 0/WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[14:30:36] [Server thread/WARN]: java.lang.LinkageError: loader constraint violation: when resolving method "me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.addMenuClickHandler(ILme/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu$MenuClickHandler;)Lme/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, io/github/sefiraat/slimetinker/items/workstations/smeltery/TinkersSmeltery, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset, have different Class objects for the type me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu$MenuClickHandler used in the signature
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.items.workstations.smeltery.TinkersSmeltery.setupMenu(TinkersSmeltery.java:74)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.infinitylib.slimefun.AbstractContainer$1.init(AbstractContainer.java:37)
[14:30:36] [Server thread/WARN]: at me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.<init>(BlockMenuPreset.java:48)
[14:30:36] [Server thread/WARN]: at me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.<init>(BlockMenuPreset.java:37)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.infinitylib.slimefun.AbstractContainer$1.<init>(AbstractContainer.java:33)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.infinitylib.slimefun.AbstractContainer.<init>(AbstractContainer.java:33)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.infinitylib.slimefun.AbstractTickingContainer.<init>(AbstractTickingContainer.java:23)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.items.workstations.smeltery.TinkersSmeltery.<init>(TinkersSmeltery.java:49)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.items.Materials.set(Materials.java:955)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.SlimeTinker.onAddonEnable(SlimeTinker.java:58)
[14:30:36] [Server thread/WARN]: at io.github.sefiraat.slimetinker.infinitylib.AbstractAddon.onEnable(AbstractAddon.java:103)
[14:30:36] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:30:36] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[14:30:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:30:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
[14:30:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
[14:30:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554)
[14:30:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
[14:30:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
[14:30:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[14:30:36] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

## Environment (Required)
I have #32 version installed on my server

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: DEV 92
 - Slimefun Version: DEV 962
 - Plugin Version:  #32

**Comment by OldLord-dev** [comment]
Okay its working now, Awesome:D Thanks so much:) didnt think that CS core lib can block other addons forSlimeFun

**Comment by Sefiraat** [comment]
Np, it stopped being required some time ago and now it actually causes issues ha. Glad it’s working.
