### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Seggan** [Sefiraat/SlimeTinker#61]
## Description (Required)

I got an error on startup. This is my server I use for generating the Slimefun item list for SFCalc Online so maybe that's the problem?

## Steps to reproduce the Issue (Required)

Just start up the server I guess...

## Server Log / Error Report

[14:30:10 ERROR]: Error occurred while enabling SlimeTinker vDEV - 35 (git 5e4c1783) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.github.sefiraat.slimetinker.items.componentmaterials.CMManager.<init>(CMManager.java:155) ~[?:?]
	at io.github.sefiraat.slimetinker.SlimeTinker.enable(SlimeTinker.java:70) ~[?:?]
	at io.github.sefiraat.slimetinker.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-136]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-136]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at io.github.sefiraat.slimetinker.items.componentmaterials.cmfactories.CMDynaTech.<clinit>(CMDynaTech.java:40) ~[?:?]
	... 13 more

## Environment (Required)

 - Minecraft Version: 1.17.1
 - Slimefun Version: 968
 - Plugin Version: 35

**Comment by Seggan** [comment]
Never mind, made a fresh install, fixed it
